### ISSUE TITLE
Cargar bibliografía Pimentón

### ISSUE THREAD

**Issue by luazuluagara** [APM-UNAL/Autopack#11]
Cargar al github bibliografía útil para el proceso de empaque, clasificación, desinfección y lavado del producto Pimentón.

**Comment by juandrsz** [comment]
En el documento pimenton.txt en la carpeta "Proceso de definición del proyecto\Base de datos de información" se encuentran los enlaces de interes, con videos del proceso, links a proveedores, y trabajos relacionados a plantas procesadoras de pimentón.
